import { createApp, version } from 'vue'
import { createStore } from 'vuex'
import { createVuestic } from 'vuestic-ui'
import { createI18n } from 'vue-i18n'
import { AgGridVue } from "ag-grid-vue3"; // Vue Data Grid Component
import { AllCommunityModule, ModuleRegistry } from 'ag-grid-community';
import 'vuestic-ui/css';

import $ from 'jquery';

import login from './login-app.vue';
import main from './main-app.vue';
import router from './router.js';

var versionApp = "1.0.5";
var vuesticVersion = "1.10.3";

console.log("FrontEnd version: " + versionApp);
console.log("Vue version: " + version);
console.log("Vuestic version: " + vuesticVersion);

ModuleRegistry.registerModules([AllCommunityModule]);

const i18n = createI18n({
    locale: 'ru',
    fallbackLocale: 'en',
    messages: {
        en: {
            message: {
                loading: 'Loading',
                release: versionApp,
                help: 'Help',
                exit: 'Exit',
                save: 'Save',
                nodata: 'No data',
                user: 'User',
                users: 'Users',
                time: 'Time',
                spaces: 'Spaces',
                space: 'Space',
                module: 'Module',
                modules: 'Modules',
                tasks: 'Tasks',
                problems: 'Problems',
                dashboards: 'Dashboards',
                rawdata: 'Metrics',
                rawtext: 'Text data',
                statusdb: 'Status DB',
                statusdm: 'Status DataManager',
                statusuim: 'Status UIManager',
                metricsld: 'Latest data (Metrics)',
                logsld: 'Latest data (Logs)',
                metricsr: 'Dynamics of metrics data in 24 hours',
                logsr: 'Dynamics of logs in 24 hours',
                noaccess: 'No access',
                available: 'Available',
                notavailable: 'Not available',
                of: 'of',
                home: 'Home',
                cancel: 'Cancel',
                delete: 'Delete',
                status: 'Status',
                description: 'Description',
                on: 'On',
                off: 'Off',
                action: 'Action',
                password: 'Password',
                message01: 'Changes are successfully preserved',
                message02: 'Failed to keep changes',
                locale: 'Select the interface language',
                settings: 'Settings',
                type: 'Type',
                notdefined: 'Not defined',
                listempty: 'List is empty',
                text: 'Text',
                number: 'Number',
                dbstatus: 'DB state',
                settings: 'Settings',
            },
            login: {
                username01: 'Enter username',
                username02: 'Username',
                password01: 'Enter password',
                password02: 'Password',
                button: 'Enter',
                message01: 'Enter user name and password...',
                message02: 'You need to enter username and password',
                message03: 'Access is allowed',
                message04: 'Username or password are indicated incorrectly',
                message05: 'Wait, system is loading...',
            },
            password: {
                change: 'Change password',
                current: 'Current password',
                new: 'New password',
                again: 'New password again',
                confirm: 'Confirm change password',
                message01: 'The password is successfully changed',
                message02: 'The current password is entered incorrectly',
                message03: 'It was not possible to change the password',
                message04: 'The new password is too short',
                message05: 'New passwords do not match',
                message06: 'Old and new passwords coincide',
                message07: 'It is necessary to fill out all the fields',
            },
            user: {
                new: 'New user',
                username: 'Username',
                firstname: 'First name',
                lastname: 'Last name',
                role: 'Role',
                userid: 'User ID',
                username: 'Username',
                logintime: 'Login time',
                ownerid: 'Owner',
                message01: 'Profile is successfully removed',
                message02: 'Failed to remove the user',
                message03: 'Enter the username',
                message04: 'Enter password',
                message05: 'User has been successfully created',
                message06: 'Failed to create a user',
                message07: 'Deleting a user',
                message08: 'User data',
                message09: 'Confirm the removal of the user',
            },
            space: {
                new: 'New space',
                id: 'Space ID',
                message01: 'Enter a descriptionof the space',
                message02: 'Select a status',
                message03: 'Space data',
                message04: 'Deleting a space',
                message05: 'The space is successfully removed',
                message06: 'Failed to remove space',
                message07: 'The space has been successfully created',
                message08: 'Failed to create a space',
                message09: 'Confirm the removal of the space',
            },
            module: {
                new: 'New module',
                id: 'ID module',
                message01: 'Module data',
                message02: 'The module is successfully removed',
                message03: 'Failed to remove the module',
                message04: 'Fill in the description',
                message05: 'The description is too long',
                message06: 'The module has been successfully created',
                message07: 'Failed to create a module',
                message08: 'Confirm the removal of the module',
                message09: 'Choose the status',
                message10: 'Enter a brief description',
                message11: 'Select the type of module',
                message12: 'Removing the module',
            },
            task: {
                new: 'New task',
                id: 'Task ID',
                object: 'Monitoring object',
                metric: 'Metric',
                interval: 'Interval',
                message01: 'Select the space',
                message02: 'Select the module',
                message03: 'Choose a monitoring object',
                message04: 'Object of Monitoring',
                message05: 'Enter the name of the metrics',
                message06: 'Metric',
                message07: 'Type of Metrics',
                message08: 'Choose the type of metric',
                message09: 'Enter the metrics collection interval',
                message10: 'Interval (sec.)',
                message11: 'Enter the value of Critical',
                message12: 'Critical value',
                message13: 'Enter the Warning value',
                message14: 'Warning value',
                message15: 'Choose the status',
                message16: 'Removing the task',
                message17: 'The task is successfully removed',
                message18: 'Failed to delete the task',
                message19: 'The task has been successfully created',
                message20: 'Failed to create a task',
                message21: 'Task data',
                message22: 'Mailing list',
                message23: 'Select a mailing list',
            },
            role: {
                superadmin: 'Super administrator',
                admin: 'Administrator',
                user: 'User'
            },
            rawdata: {
                filter01: 'Spaces',
                filter02: 'Metrics',
                filter03: 'Arbitrary filter',
                message01: 'Choose space',
                message02: 'Choose a metric',
                message03: 'Enter the value for the search',
                table01: 'Space',
                table02: 'Monitoring object',
                table03: 'Metrics',
                table04: 'Event',
                table05: 'Time of event',
                table06: 'Status',
            },
            rawtext: {
                filter01: 'Spaces',
                filter02: 'Metrics',
                filter03: 'Arbitrary filter',
                message01: 'Choose space',
                message02: 'Choose a metric',
                message03: 'Enter the value for the search',
                table01: 'Space',
                table02: 'Monitoring object',
                table03: 'Metrics',
                table04: 'Event',
                table05: 'Time of event',
                table06: 'Status',
            },
            problem: {
                table01: 'Space',
                table02: 'Module',
                table03: 'Metrics',
                table04: 'Time of event',
                table05: 'The start time of the event',
                table06: 'The meaning of the metric',
            },
            dashboard: {
                message01: 'Enter the name Dashboard',
                message02: 'The name of Dashboard',
                message03: 'The date of the beginning of the period',
                message04: 'Date endings period',
                message05: 'Start time',
                message06: 'Ending time',
                message07: 'New dashboard',
                message08: 'Delete dashboard',
                message09: 'Edit dashboard data',
                message10: 'Confirm the deletion of the dashboard',
                message11: 'Chart data',
                message12: 'Indicate the start time of the period',
                message13: 'Indicate the start date of the period',
                message14: 'Indicate the end time of the period',
                message15: 'Indicate the end date of the period',
                message16: 'The end date cannot be earlier than the start date',
                message17: 'The period cannot be more than three months',
                message18: 'Select a space for the chart',
                message19: 'Select a metric for the chart',
                message20: 'Select the type of chart for the chart',
                message21: 'Select the grouping function for the chart',
                message22: 'The dashboard has been successfully updated',
                message23: 'Failed to update the dashboard',
                message24: 'The dashboard has been successfully deleted',
                message25: 'Failed to delete the dashboard',
                message26: 'Enter the name of the dashboard',
                message27: 'The dashboard has been successfully created',
                message28: 'Failed to create a dashboard',
                message29: 'Space',
                message30: 'Select space',
                message31: 'Metrics',
                message32: 'Select metrics',
                message33: 'Chart type',
                message34: 'Chart color',
                message35: 'Grouping function',
                message36: 'Sorting',
            },
            emaillist: {
                message01: 'Enter the name of the list',
                message02: 'List name',
                message03: 'Enter the description of the list',
                message04: 'List description',
                message05: 'EMail distribution settings',
                message06: 'EMail notification list settings',
                message07: 'New list',
                message08: 'Delete list',
                message09: 'Edit list data',
                message10: 'Confirm list deletion',
                message11: 'Select list status',
                message12: 'EMail addresses',
                message13: 'EMail address',
                message14: 'Enter the name of the list',
                message15: 'List successfully created',
                message16: 'Failed to create list',
                message17: 'Enter EMail address',
                message18: 'List successfully updated',
                message19: 'Failed to update list',
                message20: 'List successfully deleted',
                message21: 'Failed to delete list',
                message22: 'Enter EMail address',
                message23: 'Description of the address',
                message24: 'Enter the description of the address',
                message25: 'Email address is entered incorrectly',
            },
            calendar: {
                monthnames: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
                firstweekday: 'Monday',
                weekdaynames: ['Su', 'Mo', 'Tu', 'We', 'Th', 'Fr', 'Sa'],
            },
        },
        ru: {
            message: {
                loading: 'Загрузка',
                release: versionApp,
                help: 'Справка',
                exit: 'Выход',
                save: 'Сохранить',
                nodata: 'Нет данных',
                user: 'Пользователь',
                users: 'Пользователи',
                time: 'Время',
                spaces: 'Пространства',
                space: 'Пространство',
                module: 'Модуль',
                modules: 'Модули',
                tasks: 'Задачи',
                problems: 'Проблемы',
                dashboards: 'Дашборды',
                rawdata: 'Метрики',
                rawtext: 'Текстовые данные',
                statusdb: 'Статус БД',
                statusdm: 'Статус DataManager',
                statusuim: 'Статус UIManager',
                metricsld: 'Последние данные (Метрики)',
                logsld: 'Последние данные (Логи)',
                metricsr: 'Динамика поступления метрик за 24 часа',
                logsr: 'Динамика поступления текстовых данных за 24 часа',
                noaccess: 'Нет доступа',
                available: 'Доступен',
                notavailable: 'Недоступен',
                of: 'из',
                home: 'Главная страница',
                cancel: 'Отменить',
                delete: 'Удалить',
                status: 'Статус',
                description: 'Описание',
                on: 'Включено',
                off: 'Выключено',
                action: 'Действие',
                password: 'Пароль',
                message01: 'Изменения успешно сохранены',
                message02: 'Не удалось сохранить изменения',
                locale: 'Выберите язык интерфейса',
                settings: 'Настройки',
                type: 'Тип',
                notdefined: 'Не определён',
                listempty: 'Список пуст',
                text: 'Текст',
                number: 'Число',
                dbstatus: 'Состояние БД',
                settings: 'Настройки',
            },
            login: {
                username01: 'Введите имя пользователя',
                username02: 'Имя пользователя',
                password01: 'Введите пароль',
                password02: 'Пароль',
                button: 'Войти',
                message01: 'Введите имя пользователя и пароль...',
                message02: 'Необходимо ввести имя пользователя и пароль',
                message03: 'Доступ разрешён',
                message04: 'Имя пользователя или пароль указаны неверно',
                message05: 'Подождите, идет загрузка системы...',
            },
            password: {
                change: 'Изменить пароль',
                current: 'Действующий пароль',
                new: 'Новый пароль',
                again: 'Новый пароль повторно',
                confirm: 'Подтвердите изменение пароля',
                message01: 'Пароль успешно изменён',
                message02: 'Действующий пароль введён неверно',
                message03: 'Не удалось изменить пароль',
                message04: 'Новый пароль слишком короткий',
                message05: 'Новые пароли не совпадают',
                message06: 'Старый и новый пароли совпадают',
                message07: 'Необходимо заполнить все поля',
            },
            user: {
                new: 'Новый пользователь',
                username: 'Имя пользователя',
                firstname: 'Имя',
                lastname: 'Фамилия',
                role: 'Роль',
                userid: 'ID профиля',
                username: 'Имя пользователя',
                logintime: 'Время входа',
                ownerid: 'Владелец',
                message01: 'Пользователь успешно удалён',
                message02: 'Не удалось удалить пользователя',
                message03: 'Введите имя пользователя',
                message04: 'Введите пароль',
                message05: 'Пользователь успешно создан',
                message06: 'Не удалось создать пользователя',
                message07: 'Удаление пользователя',
                message08: 'Данные пользователя',
                message09: 'Подтвердите удаление пользователя',
            },
            space: {
                new: 'Новое пространство',
                id: 'ID пространства',
                message01: 'Введите описание пространства',
                message02: 'Выберите статус',
                message03: 'Данные пространства',
                message04: 'Удаление пространства',
                message05: 'Пространство успешно удалено',
                message06: 'Не удалось удалить пространство',
                message07: 'Пространство успешно создано',
                message08: 'Не удалось создать пространство',
                message09: 'Подтвердите удаление пространства',
            },
            module: {
                new: 'Новый модуль',
                id: 'ID Модуля',
                message01: 'Данные модуля',
                message02: 'Модуль успешно удален',
                message03: 'Не удалось удалить модуль',
                message04: 'Заполните описание',
                message05: 'Описание слишком длинное',
                message06: 'Модуль успешно создан',
                message07: 'Не удалось создать модуль',
                message08: 'Подтвердите уаление модуля',
                message09: 'Выберите статус',
                message10: 'Введите краткое описание',
                message11: 'Выберите тип модуля',
                message12: 'Удаление модуля',
            },
            task: {
                new: 'Новая задача',
                id: 'ID задачи',
                object: 'Объект мониторинга',
                metric: 'Метрика',
                interval: 'Интервал',
                message01: 'Выберите пространство',
                message02: 'Выберите модуль',
                message03: 'Выберите объект мониторинга',
                message04: 'Объект мониторинга',
                message05: 'Введите название метрики',
                message06: 'Метрика',
                message07: 'Тип метрики',
                message08: 'Выберите тип метрики',
                message09: 'Введите интервал сбора метрик',
                message10: 'Интервал (сек.)',
                message11: 'Введите значение Critical',
                message12: 'Значение Critical',
                message13: 'Введите значение Warning',
                message14: 'Значение Warning',
                message15: 'Выберите статус',
                message16: 'Удаление задачи',
                message17: 'Задача успешно удалена',
                message18: 'Не удалось удалить задачу',
                message19: 'Задача успешно создана',
                message20: 'Не удалось создать задачу',
                message21: 'Данные задачи',
                message22: 'Список рассылки',
                message23: 'Выберите список рассылки',
            },
            role: {
                superadmin: 'Супер администратор',
                admin: 'Администратор',
                user: 'Пользователь',
            },
            rawdata: {
                filter01: 'Пространства',
                filter02: 'Метрики',
                filter03: 'Произвольный фильтр',
                message01: 'Выберите пространство',
                message02: 'Выберите метрику',
                message03: 'Введите значение для поиска',
                table01: 'Пространство',
                table02: 'Объект мониторинга',
                table03: 'Метрика',
                table04: 'Событие',
                table05: 'Время события',
                table06: 'Статус',
            },
            rawtext: {
                filter01: 'Пространства',
                filter02: 'Метрики',
                filter03: 'Произвольный фильтр',
                message01: 'Выберите пространство',
                message02: 'Выберите метрику',
                message03: 'Введите значение для поиска',
                table01: 'Пространство',
                table02: 'Объект мониторинга',
                table03: 'Метрика',
                table04: 'Событие',
                table05: 'Время события',
                table06: 'Статус',
            },
            problem: {
                table01: 'Пространство',
                table02: 'Модуль',
                table03: 'Метрика',
                table04: 'Время события',
                table05: 'Время начала события',
                table06: 'Значение метрики',
            },
            dashboard: {
                message01: 'Введите название дашборда',
                message02: 'Название дашборда',
                message03: 'Дата начала периода',
                message04: 'Дата окончания периода',
                message05: 'Время начала',
                message06: 'Время окончания',
                message07: 'Новый дашборд',
                message08: 'Удалить дашборд',
                message09: 'Редактировать данные дашборда',
                message10: 'Подтвердите удаление дашборда',
                message11: 'Данные графиков',
                message12: 'Укажите время начала периода',
                message13: 'Укажите дату начала периода',
                message14: 'Укажите время окончания периода',
                message15: 'Укажите дату окончания периода',
                message16: 'Дата окончания не может быть раньше даты начала',
                message17: 'Период не может быть больше трёх месяцев',
                message18: 'Выберите пространство для графика',
                message19: 'Выберите метрику для графика',
                message20: 'Выберите тип графика для графика',
                message21: 'Выберите функцию группировки для графика',
                message22: 'Дашборд успешно обновлён',
                message23: 'Не удалось обновить дашборд',
                message24: 'Дашборд успешно удален',
                message25: 'Не удалось удалить дашборд',
                message26: 'Введите название дашборда',
                message27: 'Дашборд успешно создан',
                message28: 'Не удалось создать дашборд',
                message29: 'Пространство',
                message30: 'Выберите пространство',
                message31: 'Метрика',
                message32: 'Выберите метрику',
                message33: 'Тип графика',
                message34: 'Цвет графика',
                message35: 'Функция группировки',
                message36: 'Сортировка',
            },
            emaillist: {
                message01: 'Введите название списка',
                message02: 'Название списка',
                message03: 'Введите описание списка',
                message04: 'Описание списка',
                message05: 'Настройка EMail рассылок',
                message06: 'Настройка списков рассылки EMail уведомлений',
                message07: 'Новый список',
                message08: 'Удалить список',
                message09: 'Редактировать данные списка',
                message10: 'Подтвердите удаление списка',
                message11: 'Выберите статус списка',
                message12: 'EMail адреса',
                message13: 'EMail адрес',
                message14: 'Введите название списка',
                message15: 'Список успешно создан',
                message16: 'Не удалось создать список',
                message17: 'Введите EMail адрес',
                message18: 'Список успешно обновлён',
                message19: 'Не удалось обновить список',
                message20: 'Список успешно удален',
                message21: 'Не удалось удалить список',
                message22: 'Введите EMail адрес',
                message23: 'Описание адреса',
                message24: 'Введите описание адреса',
                message25: 'EMail адрес введён неверно',
            },
            calendar: {
                monthnames: ['Янв', 'Фев', 'Мар', 'Апр', 'Май', 'Июн', 'Июл', 'Авг', 'Сен', 'Окт', 'Ноя', 'Дек'],
                firstweekday: 'Monday',
                weekdaynames: ['Вс', 'Пн', 'Вт', 'Ср', 'Чт', 'Пт', 'Сб'],
            },
        }
    }
});

const confVuestic = {
    config: {
        colors: {
            variables: {
                primary:"#1f303eff",
                secondary:"#36536b",
                success:"#66be33",
                info:"#3eaaf8",
                danger:"#f34030",
                warning:"#ffd952",
                backgroundPrimary:"#ffffffff",
                backgroundSecondary:"#ffffffff",
                backgroundElement:"#1f303eff",
                backgroundBorder:"#3d4c58",
                textPrimary:"#1f303eff",
                textInverted:"#ffffffff",
                shadow:"rgba(1, 1, 1, 0.30)",
                focus:"#1f303eff",
                transparent:"rgba(0, 0, 0, 0)",
                backgroundLanding:"#070d14",
                backgroundLandingBorder:"rgba(43, 49, 56, 0.8)"
            },
        },
    }   
};

const store = createStore({
    state () {
        return {
            mode: false
        }
    },
    mutations: {
        changemode (state, value) {
            state.mode = value;
        },
        changelocale (state, value) {
            state.locale = value;
        },
    }
})

if (jwtCheck() == 1) {
    const vm = createApp(main).use(store).use(router).use(i18n).use(createVuestic(confVuestic)).use(AgGridVue).use(ModuleRegistry.registerModules([AllCommunityModule])).mount('#main');
    vm.versionInfo();
    vm.userInfo();
    setTimeout(function() {
        vm.showPreloader = false;
    }, 600);
} else {
    const vm = createApp(login).use(store).use(i18n).use(createVuestic(confVuestic)).mount('#main');
    setTimeout(function() {
        vm.showPreloader = false;
    }, 600); 
}

function jwtCheck() {
    let jwtStatus = 0;
    $.ajax({
        url: "/api/v1/version?" + Math.random(),
        type: "GET",
        async: false,
        dataType: "json",
        success: function () {
            jwtStatus = 1;
        }
    });

    return jwtStatus;
}